export const projectsData = [
  {
    id: 'project-1',
    title: 'Developer landing page portfolio.',
    description: 'Interactive developer landing page portfolio built with Next.js, Tailwind, and Framer Motion, showcasing full-stack projects, resume',
    technologies: ['Next.js', 'Tailwind CSS', 'Framer Motion', "TypeScript"],
    imageUrl: '/landing.png', 
    githubLink: 'https://github.com/Gojer16/Personal-Landing-Page',
    liveLink: 'https://github.com/Gojer16/Personal-Landing-Page',
  },
  {
    id: 'project-2',
    title: 'Elevare',
    description: 'A modern productivity app designed to help you organize tasks, reflect on progress, and build better daily habits. Built with Next.js, Prisma, and Supabase, it combines a sleek interface with powerful features for personal growth.',
    technologies: ['Next.js', 'Prisma', 'Supabase', "PostgreSQL", "TypeScript", 'Tailwind CSS', 'Framer Motion'],
    imageUrl: '/elevare.png', 
    githubLink: 'https://github.com/Gojer16/Elevare',
    liveLink: 'https://elevareapp.vercel.app/',
  },
  {
    id: 'project-3',
    title: 'Weather Dashboard',
    description: 'A weather application that provides current and forecasted weather data for any location. Built with React and integrated with OpenWeatherMap API for real-time data.',
    technologies: ['React', 'CSS', 'API', "Tailwind CSS"],
    imageUrl: '/weather.png', 
    githubLink: 'https://github.com/Gojer16/Weather-Dashboard-with-Geolocation',
    liveLink: 'https://v0-weather-app-pi-three.vercel.app/',
  },
  {
    id: 'project-4',
    title: 'Personal Portfolio Website',
    description: 'Designed and developed a responsive personal portfolio to showcase projects and skills as a Software Engineer, featuring smooth animations and a modern UI.',
    technologies: ['React', 'Framer Motion', 'Tailwind CSS'],
    imageUrl: '/fourthproject.png', 
    githubLink: 'https://github.com/Gojer16/Portfolio',
    liveLink: 'https://portfolio-orlandos-projects-8aa08152.vercel.app/',
  },
];